const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const go=url=>{localStorage.setItem('lastPage',location.pathname.split('/').pop());location.href=url};
function setLang(lang){localStorage.setItem('language',lang);$$('[data-lang]').forEach(el=>el.classList.toggle('active',el.dataset.lang===lang))}
function initLang(){const lang=localStorage.getItem('language')||localStorage.getItem('lang')||'zh';$$('[data-lang]').forEach(el=>{el.onclick=()=>{setLang(el.dataset.lang);go('scanner.html')}});$$('[data-lang]').forEach(el=>el.classList.toggle('active',el.dataset.lang===lang))}
function hasLanguage(){return Boolean(localStorage.getItem('language'))}
function initAdLabel(){const lang=localStorage.getItem('language')||localStorage.getItem('lang')||'zh';const labels={zh:'贊助內容',en:'Sponsored',jp:'広告',ja:'広告'};$$('[data-ad-label]').forEach(el=>{el.textContent=labels[lang]||labels.zh})}
function initScanner(){if(!hasLanguage()){location.replace('index.html');return}initCamera()}
async function initCamera(){const video=$('#camera');if(!video)return;try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'},audio:false});video.srcObject=stream}catch(e){$('#cameraStatus').textContent='無法開啟相機，請確認瀏覽器權限。'} }
function simulateScan(scenario){const map={investment:'scenario01-investment/index.html',romance:'scenario02-romance/index.html',police:'scenario03-police/index.html',shopping:'scenario04-shopping/index.html',atm:'scenario05-atm/index.html'};$('#cameraStatus').textContent='線索辨識成功：'+({investment:'假投資詐騙',romance:'假交友詐騙',police:'假檢警詐騙',shopping:'假買家騙賣家',atm:'解除分期 / ATM'}[scenario]);setTimeout(()=>go(map[scenario]),1200)}
function runVideo(){const bar=$('#bar'),modal=$('#warningModal');if(!bar)return;let t=0,paused=false;const timer=setInterval(()=>{if(paused)return;t+=1;bar.style.width=Math.min(t*2,100)+'%';$('#sec').textContent=t;if(t===12){paused=true;modal.classList.add('show')}if(t>=50)clearInterval(timer)},300);$('#continueVideo').onclick=()=>{modal.classList.remove('show');paused=false;$('#joinLine').style.display='block'}}
function typeMessages(messages,doneSelector,options={}){const box=$('#chatBox');if(!box)return;let i=0;const messageDelay=options.messageDelay||1700,typingDelay=options.typingDelay||900;function scrollLatest(){box.scrollTop=box.scrollHeight}function showVipWarning(){const modal=$('#vipWarningModal');if(modal)modal.classList.add('show')}function showDone(){const reply=options.replySelector?$(options.replySelector):null;if(reply)reply.hidden=false;const done=$(doneSelector);if(done){done.hidden=false;done.style.display='block'}scrollLatest()}function addTyping(){const div=document.createElement('div');div.className='msg typing';div.setAttribute('aria-label','對方正在輸入');div.innerHTML='<span>對方正在輸入</span><i></i><i></i><i></i>';box.appendChild(div);scrollLatest();return div}function addMessage(m){const div=document.createElement('div');div.className='msg '+(m.type||'');div.textContent=m.text;box.appendChild(div);if(m.showVipWarning)setTimeout(showVipWarning,500);scrollLatest()}function next(){if(i>=messages.length){showDone();return}const m=messages[i++];if(m.type==='user'||m.type==='system'){addMessage(m);setTimeout(next,m.delay||messageDelay);return}const typing=addTyping();setTimeout(()=>{typing.remove();addMessage(m);setTimeout(next,m.delay||messageDelay)},m.typingDelay||typingDelay)}next()}
function moneyAnim(done){const el=$('#money');if(!el){if(done)done();return}const vals=[10000,12580,13920,15640];let i=0;function step(){el.textContent='NT$'+vals[i].toLocaleString();if(i<vals.length-1){i++;setTimeout(step,1200)}else if(done){done()}}step()}
function initProfitAnimation(){const btn=$('#withdrawBtn');if(btn)btn.hidden=true;moneyAnim(()=>{setTimeout(()=>{if(btn)btn.hidden=false},1600)})}
function chooseQuiz(ans){go(ans==='A'?'scene01_quiz_wrong.html':'scene01_quiz_right.html')}
if('serviceWorker' in navigator){const swUrl=new URL('../sw.js',document.currentScript.src).href;navigator.serviceWorker.register(swUrl).catch(()=>{})}
function fitStage(){let stage=document.body.firstElementChild;while(stage&&stage.tagName==='SCRIPT')stage=stage.nextElementSibling;if(!stage)return;const fitWidth=document.body.dataset.fit==='width';stage.style.transform='none';stage.style.maxHeight='';stage.style.overflowY='';const rect=stage.getBoundingClientRect();const vw=window.innerWidth,vh=window.innerHeight;let scale;if(fitWidth){scale=vw/rect.width;if(rect.height*scale>vh){stage.style.maxHeight=(vh/scale)+'px';stage.style.overflowY='auto'}}else{scale=Math.min(vw/rect.width,vh/rect.height)}stage.style.position='fixed';stage.style.left='50%';stage.style.top='50%';stage.style.transformOrigin='center center';stage.style.transform=`translate(-50%,-50%) scale(${scale})`}
window.addEventListener('load',fitStage);window.addEventListener('resize',fitStage);window.addEventListener('orientationchange',fitStage);fitStage();
