const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const go=url=>{localStorage.setItem('lastPage',location.pathname.split('/').pop());location.href=url};
function setLang(lang){localStorage.setItem('lang',lang);$$('[data-lang]').forEach(el=>el.classList.toggle('active',el.dataset.lang===lang))}
function initLang(){const lang=localStorage.getItem('lang')||'zh';$$('[data-lang]').forEach(el=>{el.onclick=()=>setLang(el.dataset.lang)});setLang(lang)}
async function initCamera(){const video=$('#camera');if(!video)return;try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'},audio:false});video.srcObject=stream}catch(e){$('#cameraStatus').textContent='無法開啟相機，請確認瀏覽器權限。'} }
function simulateScan(scenario){const map={investment:'scenario01-investment/index.html',romance:'scenario02-romance/index.html',police:'scenario03-police/index.html',shopping:'scenario04-shopping/index.html',atm:'scenario05-atm/index.html'};$('#cameraStatus').textContent='線索辨識成功：'+({investment:'假投資詐騙',romance:'假交友詐騙',police:'假檢警詐騙',shopping:'假買家騙賣家',atm:'解除分期 / ATM'}[scenario]);setTimeout(()=>go(map[scenario]),1200)}
function runVideo(){const bar=$('#bar'),modal=$('#warningModal');if(!bar)return;let t=0,paused=false;const timer=setInterval(()=>{if(paused)return;t+=1;bar.style.width=Math.min(t*2,100)+'%';$('#sec').textContent=t;if(t===12){paused=true;modal.classList.add('show')}if(t>=50)clearInterval(timer)},300);$('#continueVideo').onclick=()=>{modal.classList.remove('show');paused=false;$('#joinLine').style.display='block'}}
function typeMessages(messages,doneSelector){const box=$('#chatBox');if(!box)return;let i=0;function next(){if(i>=messages.length){const done=$(doneSelector); if(done)done.style.display='block';return}const m=messages[i++];const div=document.createElement('div');div.className='msg '+(m.type||'');div.textContent=m.text;box.appendChild(div);box.scrollTop=box.scrollHeight;setTimeout(next,m.delay||900)}next()}
function moneyAnim(){const el=$('#money');if(!el)return;const vals=[10000,12580,13920,15640];let i=0;function step(){el.textContent='NT$'+vals[i].toLocaleString();if(i<vals.length-1){i++;setTimeout(step,700)}}step()}
function chooseQuiz(ans){go(ans==='A'?'scene01_quiz_wrong.html':'scene01_quiz_right.html')}
if('serviceWorker' in navigator){navigator.serviceWorker.register('/sw.js').catch(()=>{})}
